/**
 * Alumni Institutional Impact & Accreditation Analytics (C7) — types & registry.
 *
 * Zero fabrication: no hard-coded NBA/NAAC criterion numbers.
 * Activity ≠ engagement ≠ opportunity ≠ outcome ≠ impact without evidence.
 */
import { z } from 'zod';

export const IMPACT_DOMAINS = [
  'ALUMNI_BASE',
  'DATA_QUALITY',
  'ENGAGEMENT',
  'MENTORSHIP',
  'CAREER_GUIDANCE',
  'RECRUITMENT',
  'INTERNSHIP',
  'EXPERT_ENGAGEMENT',
  'PROJECT_SUPPORT',
  'INDUSTRY_CONNECT',
  'RESEARCH_COLLABORATION',
  'INNOVATION_STARTUP',
  'BOS_CURRICULUM',
  'INSTITUTIONAL_COLLABORATION',
  'COMMUNITY',
  'RECOGNITION',
  'ALUMNI_VALUE',
  'CONTRIBUTION',
  'STUDENT_IMPACT',
  'DEPARTMENT_IMPACT',
  'OTHER',
] as const;
export type ImpactDomain = (typeof IMPACT_DOMAINS)[number];

export const CALCULATION_TYPES = [
  'COUNT',
  'RATE',
  'UNIQUE_COUNT',
  'SUM',
  'FUNNEL_STAGE',
  'RATIO',
] as const;

export const METRIC_UNITS = ['count', 'percent', 'ratio', 'hours', 'currency_ref'] as const;

export const ATTRIBUTION_LEVELS = ['DIRECT', 'SUPPORTED', 'ASSOCIATED', 'UNKNOWN'] as const;
export type AttributionLevel = (typeof ATTRIBUTION_LEVELS)[number];

export const PERIOD_TYPES = ['ACADEMIC_YEAR', 'CALENDAR_YEAR', 'SEMESTER', 'CUSTOM'] as const;
export type PeriodType = (typeof PERIOD_TYPES)[number];

export const EVIDENCE_SOURCE_TYPES = [
  'C1_PROFILE',
  'C2_OUTCOME',
  'C2_INTERACTION',
  'C4_CAMPAIGN',
  'C5_NEED',
  'C5_FULFILMENT',
  'C6_RECOGNITION',
  'C6_VALUE',
  'C6_COMMUNITY',
  'FINANCE_REF',
  'PLACEMENT_REF',
  'STUDENT_PROJECT',
  'OTHER',
] as const;

export const LEDGER_VERIFICATION = [
  'UNVERIFIED',
  'PENDING',
  'VERIFIED',
  'REJECTED',
  'PROJECTED',
] as const;

export const GAP_TYPES = [
  'OUTCOME_WITHOUT_EVIDENCE',
  'EVIDENCE_UNVERIFIED',
  'MISSING_BENEFICIARY_LINK',
  'MISSING_DEPARTMENT_LINK',
  'STALE_PROFILE_DEPENDENCY',
  'ATTRIBUTION_UNKNOWN',
  'METRIC_SOURCE_INCOMPLETE',
] as const;

export const REPORT_TYPES = [
  'ANNUAL_IMPACT',
  'DEPARTMENT',
  'MENTORSHIP',
  'RECRUITMENT_INTERNSHIP',
  'EXPERT_INDUSTRY',
  'RECOGNITION_VALUE',
  'ACCREDITATION_EVIDENCE',
  'DATA_QUALITY',
  'CUSTOM',
] as const;

export const WORKSPACE_VIEWS = [
  'EXECUTIVE',
  'PRINCIPAL',
  'MANAGEMENT',
  'HOD',
  'OPERATIONS',
  'IQAC',
  'DEPARTMENT',
  'TRENDS',
  'FUNNELS',
  'EVIDENCE',
  'GAPS',
  'ACCREDITATION',
  'REPORTS',
  'REGISTRY',
] as const;

export const SUPPORTED_DIMENSIONS = [
  'institution',
  'department',
  'programme',
  'batch',
  'graduation_year',
] as const;

/**
 * Meaningful engagement (v1): at least one CRM interaction flagged
 * is_meaningful_engagement=true, OR relationship.last_engagement_at within
 * lookback, OR verified CRM outcome in period.
 * Explicitly EXCLUDES: system notifications, profile page views, campaign targeting alone.
 */
export const MEANINGFUL_ENGAGEMENT_DEFINITION_V1 =
  'At least one CRM interaction with is_meaningful_engagement=true OR relationship last_engagement_at within lookback months OR a verified CRM outcome in the reporting period. Excludes system notifications, profile views, and campaign targeting alone.';

export type MetricDefinitionSeed = {
  metricKey: string;
  name: string;
  description: string;
  impactDomain: ImpactDomain;
  calculationType: (typeof CALCULATION_TYPES)[number];
  numeratorDefinition?: string | null;
  denominatorDefinition?: string | null;
  unit: (typeof METRIC_UNITS)[number];
  sourceModules: string[];
  evidenceRequirements: string;
  supportedDimensions: string[];
  freshnessExpectations: string;
  version: number;
  activeFrom: string;
};

/** Central metric registry — do not scatter KPI definitions in UI. */
export const METRIC_REGISTRY: MetricDefinitionSeed[] = [
  {
    metricKey: 'alumni.total',
    name: 'Total Alumni',
    description: 'Eligible alumni profiles in lifecycle (non-archived) for the institution/filter.',
    impactDomain: 'ALUMNI_BASE',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_profiles rows',
    supportedDimensions: ['institution', 'department', 'programme', 'batch', 'graduation_year'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.verified',
    name: 'Verified Alumni',
    description: 'Alumni with verification_state = VERIFIED.',
    impactDomain: 'ALUMNI_BASE',
    calculationType: 'COUNT',
    numeratorDefinition: 'verification_state = VERIFIED',
    denominatorDefinition: 'alumni.total (eligible population)',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_profiles.verification_state',
    supportedDimensions: ['institution', 'department', 'programme', 'batch', 'graduation_year'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.verified_rate',
    name: 'Verified Alumni Rate',
    description: 'Verified alumni / eligible alumni population. Always display numerator/denominator.',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'RATE',
    numeratorDefinition: 'alumni.verified',
    denominatorDefinition: 'alumni.total',
    unit: 'percent',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_profiles',
    supportedDimensions: ['institution', 'department', 'programme', 'batch', 'graduation_year'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.reachable',
    name: 'Reachable Alumni',
    description: 'Alumni with usable contact (email or phone) and not marked unreachable/archived.',
    impactDomain: 'ALUMNI_BASE',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_profiles email + phone_override / student phone / contact_verified_at',
    supportedDimensions: ['institution', 'department', 'programme', 'batch', 'graduation_year'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.unreachable',
    name: 'Unreachable Alumni',
    description: 'Alumni lacking both email and phone, or lifecycle indicating unreachable.',
    impactDomain: 'ALUMNI_BASE',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_profiles contact fields',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.profile_current',
    name: 'Current Profiles',
    description: 'Profiles with freshness state not STALE (C1 freshness config).',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'C1 freshness / contact_verified_at / employment verification',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Depends on alumni_freshness_config',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.profile_stale',
    name: 'Stale Profiles',
    description: 'Profiles classified STALE by C1 freshness rules. Not the same as inactive alumni.',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'C1 freshness',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Depends on alumni_freshness_config',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.career_coverage',
    name: 'Career Coverage',
    description: 'Alumni with at least one employment / higher-studies / entrepreneurship record.',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'RATE',
    numeratorDefinition: 'Alumni with career record',
    denominatorDefinition: 'alumni.total',
    unit: 'percent',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_employment / higher_studies / entrepreneurship',
    supportedDimensions: ['institution', 'department', 'graduation_year'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.contact_coverage',
    name: 'Contact Coverage',
    description: 'Alumni with email or phone on file.',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'RATE',
    numeratorDefinition: 'Alumni with email or phone',
    denominatorDefinition: 'alumni.total',
    unit: 'percent',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_profiles contact fields',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.willingness_coverage',
    name: 'Willingness Coverage',
    description: 'Alumni with at least one willingness / capability preference recorded.',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'RATE',
    numeratorDefinition: 'Alumni with willingness/capability rows',
    denominatorDefinition: 'alumni.total',
    unit: 'percent',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_interest_capabilities / profile willingness cols',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.capability_coverage',
    name: 'Capability Coverage',
    description: 'Alumni with structured capability domains recorded.',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'RATE',
    numeratorDefinition: 'Alumni with capability domains',
    denominatorDefinition: 'alumni.total',
    unit: 'percent',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_interest_capabilities',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'alumni.identity_unresolved',
    name: 'Unresolved Identity Candidates',
    description: 'Open duplicate/identity merge candidates (C1).',
    impactDomain: 'DATA_QUALITY',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C1'],
    evidenceRequirements: 'alumni_identity_candidates',
    supportedDimensions: ['institution'],
    freshnessExpectations: 'Real-time from C1',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.contacted',
    name: 'Unique Alumni Contacted',
    description: 'Distinct alumni with last_contact_at set (C2 relationships).',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_relationships.last_contact_at',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.responded',
    name: 'Unique Alumni Responded',
    description: 'Distinct alumni with last_response_at set.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_relationships.last_response_at',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.active_alumni',
    name: 'Meaningfully Engaged Alumni',
    description: MEANINGFUL_ENGAGEMENT_DEFINITION_V1,
    impactDomain: 'ENGAGEMENT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C4'],
    evidenceRequirements: 'CRM meaningful interactions / last_engagement_at / verified outcomes',
    supportedDimensions: ['institution', 'department', 'graduation_year'],
    freshnessExpectations: 'Real-time; lookback configurable',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.repeat_alumni',
    name: 'Repeat-Engaged Alumni',
    description: 'Alumni in relationship_stage REPEAT_ENGAGEMENT.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_relationships.relationship_stage',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.response_rate',
    name: 'Response Rate',
    description: 'Responded / contacted. Display n/d.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'RATE',
    numeratorDefinition: 'engagement.responded',
    denominatorDefinition: 'engagement.contacted',
    unit: 'percent',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_relationships',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.open_followups',
    name: 'Open Follow-ups',
    description: 'CRM follow-ups in OPEN/IN_PROGRESS/OVERDUE.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_crm_followups',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.overdue_followups',
    name: 'Overdue Follow-ups',
    description: 'CRM follow-ups past due.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_crm_followups',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.programs',
    name: 'Engagement Programs',
    description: 'C4 engagement programs in period (not outcomes).',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C4'],
    evidenceRequirements: 'alumni_engagement_programs',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C4',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.campaigns',
    name: 'Engagement Campaigns',
    description: 'C4 campaigns in period.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C4'],
    evidenceRequirements: 'alumni_engagement_campaigns',
    supportedDimensions: ['institution'],
    freshnessExpectations: 'Real-time from C4',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'engagement.opportunity_conversion',
    name: 'Opportunity Conversion',
    description: 'Completed CRM opportunities / active+completed opportunities.',
    impactDomain: 'ENGAGEMENT',
    calculationType: 'RATE',
    numeratorDefinition: 'Completed opportunities',
    denominatorDefinition: 'Active + completed opportunities',
    unit: 'percent',
    sourceModules: ['C2'],
    evidenceRequirements: 'alumni_crm_opportunities',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C2',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'mentorship.alumni_mentors',
    name: 'Alumni Mentors',
    description: 'Unique alumni with verified STUDENTS_MENTORED outcomes (not invitations/willingness).',
    impactDomain: 'MENTORSHIP',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2 outcomes STUDENTS_MENTORED and/or verified C5 fulfilment',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'mentorship.students_supported',
    name: 'Students Mentored',
    description: 'Sum of verified STUDENTS_MENTORED quantities; beneficiary drill-down when linked.',
    impactDomain: 'MENTORSHIP',
    calculationType: 'SUM',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified outcomes quantity / C5 beneficiaries',
    supportedDimensions: ['institution', 'department', 'programme'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'mentorship.completed_cycles',
    name: 'Completed Mentoring Cycles',
    description: 'Count of verified STUDENTS_MENTORED outcome records (each = one evidenced cycle).',
    impactDomain: 'MENTORSHIP',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'Verified C2 STUDENTS_MENTORED',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'recruitment.alumni_recruiters',
    name: 'Alumni Recruiters / Connectors',
    description: 'Unique alumni with verified PLACEMENTS_SUPPORTED or JOBS_REFERRED. Terminology: ALUMNI_SUPPORTED — not causal placement claim.',
    impactDomain: 'RECRUITMENT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2 outcomes',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'recruitment.opportunities',
    name: 'Recruitment Opportunities Facilitated',
    description: 'CRM opportunities of recruitment types completed, or verified placement/job outcomes.',
    impactDomain: 'RECRUITMENT',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'CRM opportunities / verified outcomes',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'recruitment.placements_supported',
    name: 'Placements Supported (Alumni)',
    description: 'Sum of verified PLACEMENTS_SUPPORTED quantities. Reported as ALUMNI_SUPPORTED — does not claim placement causation. Attribution default SUPPORTED unless DIRECT evidence.',
    impactDomain: 'RECRUITMENT',
    calculationType: 'SUM',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'Verified C2 PLACEMENTS_SUPPORTED — does not claim causation',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'internship.alumni_enablers',
    name: 'Alumni Internship Enablers',
    description: 'Unique alumni with verified INTERNSHIPS_ENABLED. Promised capacity ≠ verified.',
    impactDomain: 'INTERNSHIP',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2 / verified C5 fulfilment',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'internship.positions_enabled',
    name: 'Internship Positions Enabled',
    description: 'Sum of verified INTERNSHIPS_ENABLED quantities.',
    impactDomain: 'INTERNSHIP',
    calculationType: 'SUM',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified outcomes / fulfilment verified_quantity',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'internship.students_benefited',
    name: 'Internship Students Benefited',
    description: 'Unique students linked as beneficiaries on internship needs/outcomes when available; else quantity sum labelled as interactions.',
    impactDomain: 'INTERNSHIP',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'C5 beneficiaries / outcome beneficiary_refs',
    supportedDimensions: ['institution', 'department', 'programme'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'experts.sessions_delivered',
    name: 'Expert Sessions Delivered',
    description: 'Verified EXPERT_SESSIONS_DELIVERED outcomes. Invitation ≠ delivered.',
    impactDomain: 'EXPERT_ENGAGEMENT',
    calculationType: 'SUM',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2 EXPERT_SESSIONS_DELIVERED',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'experts.unique_alumni',
    name: 'Unique Alumni Experts',
    description: 'Distinct alumni with verified expert session outcomes.',
    impactDomain: 'EXPERT_ENGAGEMENT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'Verified C2 EXPERT_SESSIONS_DELIVERED',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'projects.alumni_mentors',
    name: 'Alumni Project Mentors',
    description: 'Unique alumni with verified PROJECTS_SUPPORTED. Uses student_projects as authoritative project SoT when linked.',
    impactDomain: 'PROJECT_SUPPORT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2 PROJECTS_SUPPORTED',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'projects.supported',
    name: 'Projects Supported',
    description: 'Sum of verified PROJECTS_SUPPORTED quantities.',
    impactDomain: 'PROJECT_SUPPORT',
    calculationType: 'SUM',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified outcomes',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'research.collaborations',
    name: 'Research Collaborations (Evidence-backed)',
    description: 'Verified RESEARCH_COLLABORATIONS outcomes only. No dedicated Research module — label source clearly.',
    impactDomain: 'RESEARCH_COLLABORATION',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2/C5 only — no unstructured claims',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'bos.participation',
    name: 'BoS / Curriculum Participation',
    description: 'Verified BOS_PARTICIPATION outcomes only. No dedicated BoS module.',
    impactDomain: 'BOS_CURRICULUM',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2/C5 only',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'innovation.founders_engaged',
    name: 'Alumni Founders Engaged',
    description: 'Alumni with C1 entrepreneurship evidence who also have meaningful engagement or verified STARTUP_SUPPORT.',
    impactDomain: 'INNOVATION_STARTUP',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C1', 'C2'],
    evidenceRequirements: 'C1 entrepreneurship + engagement/outcome evidence',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'innovation.startup_support',
    name: 'Startup Support Engagements',
    description: 'Verified STARTUP_SUPPORT outcomes. No funding/investment estimates.',
    impactDomain: 'INNOVATION_STARTUP',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2/C5',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'industry.connections',
    name: 'Industry Connections (Verified)',
    description: 'Verified INDUSTRY_VISITS / MoU-related outcomes. Stages: INTRODUCED / IN_PROGRESS / VERIFIED_OUTCOME separated in drill-down.',
    impactDomain: 'INDUSTRY_CONNECT',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2', 'C5'],
    evidenceRequirements: 'Verified C2 INDUSTRY_VISITS and related opportunities',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'recognition.alumni_recognised',
    name: 'Alumni Recognised',
    description: 'Issued/corrected C6 recognition records (not nominations).',
    impactDomain: 'RECOGNITION',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C6'],
    evidenceRequirements: 'alumni_recognition_records status ISSUED/CORRECTED',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C6',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'recognition.value_participants',
    name: 'Value Program Participants',
    description: 'Alumni with C6 value participation beyond VIEWED (VIEWED not tracked).',
    impactDomain: 'ALUMNI_VALUE',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C6'],
    evidenceRequirements: 'alumni_value_participations',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C6',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'contribution.financial_refs',
    name: 'Financial Contribution References',
    description: 'Count of verified FINANCIAL_CONTRIBUTION outcomes referencing Finance SoT. No invented monetary totals.',
    impactDomain: 'CONTRIBUTION',
    calculationType: 'COUNT',
    unit: 'currency_ref',
    sourceModules: ['C2', 'Finance'],
    evidenceRequirements: 'Verified FINANCIAL_CONTRIBUTION with finance reference',
    supportedDimensions: ['institution'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'contribution.non_financial',
    name: 'Non-Financial Contributions',
    description: 'Verified NON_FINANCIAL_CONTRIBUTION plus other verified contribution-type outcomes. No invented monetary value.',
    impactDomain: 'CONTRIBUTION',
    calculationType: 'COUNT',
    unit: 'count',
    sourceModules: ['C2'],
    evidenceRequirements: 'Verified C2 outcomes',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time; VERIFIED only',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'students.unique_benefited',
    name: 'Unique Students Benefited',
    description: 'Deduped student beneficiaries across mentorship/internship/recruitment/projects/experts where linkage exists.',
    impactDomain: 'STUDENT_IMPACT',
    calculationType: 'UNIQUE_COUNT',
    unit: 'count',
    sourceModules: ['C5', 'C2'],
    evidenceRequirements: 'alumni_connect_beneficiaries / outcome beneficiary_refs',
    supportedDimensions: ['institution', 'department', 'programme'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'students.beneficiary_interactions',
    name: 'Total Beneficiary Interactions',
    description: 'Total beneficiary linkage rows / outcome quantities — may double-count students across domains.',
    impactDomain: 'STUDENT_IMPACT',
    calculationType: 'SUM',
    unit: 'count',
    sourceModules: ['C5', 'C2'],
    evidenceRequirements: 'Beneficiary links + outcome quantities',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'needs.open',
    name: 'Open Connect Needs',
    description: 'C5 needs not fulfilled/cancelled.',
    impactDomain: 'DEPARTMENT_IMPACT',
    calculationType: 'FUNNEL_STAGE',
    unit: 'count',
    sourceModules: ['C5'],
    evidenceRequirements: 'alumni_connect_needs',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C5',
    version: 1,
    activeFrom: '2026-10-12',
  },
  {
    metricKey: 'needs.fulfilled',
    name: 'Fulfilled Connect Needs',
    description: 'C5 needs with fulfilled status.',
    impactDomain: 'DEPARTMENT_IMPACT',
    calculationType: 'FUNNEL_STAGE',
    unit: 'count',
    sourceModules: ['C5'],
    evidenceRequirements: 'alumni_connect_needs / fulfilment',
    supportedDimensions: ['institution', 'department'],
    freshnessExpectations: 'Real-time from C5',
    version: 1,
    activeFrom: '2026-10-12',
  },
];

export const SOURCE_OF_TRUTH_MATRIX = [
  { capability: 'Alumni identity / verification / contact / freshness', authoritative: 'C1 alumni_profiles + provenance', c7Role: 'PROJECT', notes: 'Health metrics only; incomplete ≠ inactive' },
  { capability: 'Career / employment / entrepreneurship', authoritative: 'C1 alumni_employment / higher_studies / entrepreneurship', c7Role: 'PROJECT', notes: 'Coverage metrics; not impact' },
  { capability: 'CRM relationships / meaningful engagement', authoritative: 'C2 alumni_relationships + interactions', c7Role: 'PROJECT', notes: 'Meaningful engagement definition versioned' },
  { capability: 'Verified outcomes', authoritative: 'C2 alumni_crm_outcomes VERIFIED', c7Role: 'PRIMARY IMPACT SOURCE', notes: 'Attribution levels required' },
  { capability: 'Engagement programs / campaigns / funnels', authoritative: 'C4', c7Role: 'PROJECT', notes: 'Targeting ≠ engagement' },
  { capability: 'Connect needs / fulfilment / beneficiaries', authoritative: 'C5', c7Role: 'PROJECT', notes: 'Promised ≠ verified; need-to-impact funnel' },
  { capability: 'Recognition / value / communities', authoritative: 'C6', c7Role: 'PROJECT', notes: 'Alumni→Institution vs Institution→Alumni separate; no reciprocity score' },
  { capability: 'Institutional placement rate', authoritative: 'placement/analytics', c7Role: 'REFERENCE ONLY', notes: 'Never fork placement %' },
  { capability: 'Mentoring coverage (institutional)', authoritative: 'mentoring module', c7Role: 'REFERENCE ONLY', notes: 'No alumni_profile FK; alumni mentorship from C2/C5' },
  { capability: 'Finance fee collection', authoritative: 'finance/reports', c7Role: 'REFERENCE ONLY', notes: 'Alumni financial contribution only via authoritative refs' },
  { capability: 'Student projects', authoritative: 'placement student_projects', c7Role: 'REFERENCE', notes: 'Do not duplicate project rows' },
  { capability: 'Research / BoS / Startup ERP modules', authoritative: 'NONE', c7Role: 'LIMITATION', notes: 'Only verified C2/C5 evidence' },
  { capability: 'NBA/NAAC criterion catalogue', authoritative: 'Configurable C7 frameworks', c7Role: 'OWN (empty until configured)', notes: 'Zero fabrication of criterion numbers' },
  { capability: 'Academic year masters', authoritative: 'academic_years', c7Role: 'REUSE', notes: 'Default reporting uses is_current' },
  { capability: 'Department / programme masters', authoritative: 'departments / programs', c7Role: 'REUSE', notes: 'No shadow tables' },
  { capability: 'Management executive KPIs', authoritative: 'management/overview', c7Role: 'LINK / NEW KEYS ONLY', notes: 'Do not redefine student/faculty/fee KPIs' },
  { capability: 'IQAC / NBA roles', authoritative: 'FACULTY_ROLES', c7Role: 'REUSE ACCESS', notes: 'No new IQAC portal/role' },
  { capability: 'Metric definitions / versions', authoritative: 'C7 METRIC_REGISTRY + alumni_impact_metric_defs', c7Role: 'OWN', notes: 'Never silently redefine history' },
  { capability: 'Evidence ledger', authoritative: 'C7 projection of C1–C6', c7Role: 'OWN (projection)', notes: 'Prefer reference over copy' },
  { capability: 'Report snapshots', authoritative: 'C7 alumni_impact_report_snapshots', c7Role: 'OWN', notes: 'Immutable historical definitions' },
] as const;

export const FORBIDDEN_IMPACT_CLAIMS = [
  'placement_caused_by_alumnus_without_evidence',
  'invented_nba_naac_criteria',
  'invented_research_publications',
  'invented_bos_participation',
  'invented_startup_funding',
  'invented_mou',
  'monetary_value_of_non_financial',
  'reciprocity_score',
  'best_department_leaderboard',
  'activity_as_impact',
  'promised_as_verified_outcome',
  'associated_reported_as_direct',
] as const;

export const KNOWN_LIMITATIONS = [
  'No dedicated Research module — research metrics only from verified C2/C5.',
  'No dedicated BoS module — BoS metrics only from verified C2/C5.',
  'No dedicated Startup module — no funding/investment estimates.',
  'No hard-coded NBA/NAAC criterion numbers — frameworks are institution-configured.',
  'Institutional mentoring module has no alumni_profile FK — alumni mentorship from C2/C5.',
  'Institutional placement % remains placement/analytics SoT — C7 reports ALUMNI_SUPPORTED only.',
  'C4 external channels remain MANUAL_ONLY/UNAVAILABLE (inherited from C4/C6).',
  'No VIEWED participation telemetry (C6).',
  'No LinkedIn/social enrichment (C6).',
  'PDF export not guaranteed — CSV/JSON via existing patterns.',
] as const;

export type ImpactPeriod = {
  periodType: PeriodType;
  periodLabel: string | null;
  start: string | null;
  end: string | null;
  complete: boolean;
  academicYearId?: number | null;
  academicYearLabel?: string | null;
  coverageNote?: string | null;
};

export type MetricResult = {
  metricKey: string;
  name: string;
  version: number;
  impactDomain: ImpactDomain;
  value: number | null;
  numerator: number | null;
  denominator: number | null;
  unit: string;
  definition: string;
  sourceModules: string[];
  attributionDefault: AttributionLevel;
  period: ImpactPeriod;
  noData?: boolean;
  dataQualityNote?: string | null;
  drilldownKey?: string | null;
};

export const periodQuerySchema = z.object({
  periodType: z.enum(PERIOD_TYPES).optional(),
  periodLabel: z.string().trim().max(64).optional().nullable(),
  start: z.string().min(8).max(16).optional().nullable(),
  end: z.string().min(8).max(16).optional().nullable(),
  academicYearId: z.number().int().positive().optional().nullable(),
  departmentId: z.number().int().positive().optional().nullable(),
  programmeId: z.number().int().positive().optional().nullable(),
  batch: z.string().trim().max(64).optional().nullable(),
  graduationYear: z.number().int().min(1950).max(2100).optional().nullable(),
  impactDomain: z.enum(IMPACT_DOMAINS).optional().nullable(),
  metricKey: z.string().trim().max(96).optional().nullable(),
  view: z.enum(WORKSPACE_VIEWS).optional(),
}).strict();

export const frameworkCreateSchema = z.object({
  code: z.string().trim().min(1).max(48),
  label: z.string().trim().min(1).max(255),
  description: z.string().trim().max(4000).optional().nullable(),
}).strict();

export const criterionCreateSchema = z.object({
  frameworkId: z.number().int().positive(),
  code: z.string().trim().min(1).max(64),
  label: z.string().trim().min(1).max(255),
  parentCode: z.string().trim().max(64).optional().nullable(),
  description: z.string().trim().max(4000).optional().nullable(),
  sortOrder: z.number().int().optional(),
}).strict();

export const mappingCreateSchema = z.object({
  frameworkId: z.number().int().positive(),
  criterionId: z.number().int().positive(),
  metricKey: z.string().trim().max(96).optional().nullable(),
  impactDomain: z.enum(IMPACT_DOMAINS).optional().nullable(),
  outcomeType: z.string().trim().max(64).optional().nullable(),
  academicYear: z.string().trim().max(32).optional().nullable(),
  evidenceReferences: z.array(z.string().max(512)).max(50).optional(),
  notes: z.string().trim().max(4000).optional().nullable(),
}).strict();

export const mappingVerifySchema = z.object({
  verificationStatus: z.enum(['DRAFT', 'ACTIVE', 'VERIFIED', 'ARCHIVED']),
}).strict();

export const snapshotCreateSchema = z.object({
  reportType: z.enum(REPORT_TYPES),
  title: z.string().trim().min(1).max(255),
  periodType: z.enum(PERIOD_TYPES).optional(),
  periodLabel: z.string().trim().max(64).optional().nullable(),
  start: z.string().min(8).max(16).optional().nullable(),
  end: z.string().min(8).max(16).optional().nullable(),
  departmentId: z.number().int().positive().optional().nullable(),
  programmeId: z.number().int().positive().optional().nullable(),
  batch: z.string().trim().max(64).optional().nullable(),
  graduationYear: z.number().int().optional().nullable(),
  impactDomain: z.enum(IMPACT_DOMAINS).optional().nullable(),
  metricKeys: z.array(z.string().max(96)).max(80).optional(),
}).strict();

export const reportBuildSchema = z.object({
  reportType: z.enum(REPORT_TYPES),
  periodType: z.enum(PERIOD_TYPES).optional(),
  periodLabel: z.string().trim().max(64).optional().nullable(),
  start: z.string().min(8).max(16).optional().nullable(),
  end: z.string().min(8).max(16).optional().nullable(),
  academicYearId: z.number().int().positive().optional().nullable(),
  departmentId: z.number().int().positive().optional().nullable(),
  programmeId: z.number().int().positive().optional().nullable(),
  batch: z.string().trim().max(64).optional().nullable(),
  graduationYear: z.number().int().optional().nullable(),
  impactDomain: z.enum(IMPACT_DOMAINS).optional().nullable(),
  createSnapshot: z.boolean().optional(),
}).strict();
