import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../../lib/api';
import { Button, Input, PageHeader, Surface } from '../../components/ui';
import { StatusPill, statusToneFor } from '../lms/studentUi';
import { useDocumentTitle } from '../../lib/useDocumentTitle';

type Dashboard = { actionRequired: Record<string, number>; today: { issued: number }; files: number };
export function OfficeDashboardPage() { const [d, setD] = useState<Dashboard | null>(null); useDocumentTitle('Office Administration'); useEffect(() => { api<Dashboard>('/api/office/dashboard').then(setD); }, []); return <div className="space-y-6"><PageHeader title="Office Administration" subtitle="College office operations, requests, registers, and dispatch" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{d ? Object.entries({ ...d.actionRequired, issued: d.today.issued, files: d.files }).map(([k,v]) => <Surface key={k}><p className="text-2xl font-semibold">{v}</p><p className="text-xs uppercase text-ink-muted">{k.replace(/([A-Z])/g,' $1')}</p></Surface>) : <Surface>Loading…</Surface>}</div><div className="grid gap-4 md:grid-cols-3"><Surface><h2 className="mb-3 font-semibold">Action required</h2><p className="text-sm text-ink-muted">Review requests, acknowledge inward correspondence, and complete dispatches.</p><Link className="mt-4 inline-block text-sm text-accent" to="/office/requests">Open request inbox →</Link></Surface><Surface><h2 className="mb-3 font-semibold">Registers</h2><div className="flex gap-3 text-sm"><Link className="text-accent" to="/office/inward">Inward</Link><Link className="text-accent" to="/office/outward">Outward</Link></div></Surface><Surface><h2 className="mb-3 font-semibold">Records</h2><Link className="text-sm text-accent" to="/office/files">Track file movement →</Link></Surface></div></div>; }

export function OfficeRequestsPage() { const [rows, setRows] = useState<any[]>([]); const [status, setStatus] = useState(''); useDocumentTitle('Office Request Inbox'); useEffect(() => { api<{requests:any[]}>(`/api/office/requests${status ? `?status=${status}` : ''}`).then(d=>setRows(d.requests)).catch(()=>setRows([])); },[status]); return <div className="space-y-5"><PageHeader title="Request Inbox" subtitle="Student and academic service requests routed to the college office" /><div className="flex gap-2"><select className="rounded border border-border bg-surface px-3 py-2 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['SUBMITTED','UNDER_REVIEW','ACTION_REQUIRED','APPROVED','READY','COMPLETED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></div><Surface className="overflow-x-auto p-0"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-ink-muted"><tr><th className="p-3">Request</th><th className="p-3">Requester</th><th className="p-3">Type</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3"><Link className="font-medium text-accent" to={`/office/requests/${r.id}`}>{r.requestNumber || `#${r.id}`}</Link><div>{r.title}</div></td><td className="p-3">{r.studentName}<div className="text-xs text-ink-muted">{r.usn}</div></td><td className="p-3">{r.requestTypeLabel}</td><td className="p-3"><StatusPill tone={statusToneFor(r.status)}>{r.status}</StatusPill></td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-sm text-ink-muted">No requests match this filter.</p>}</Surface></div>; }

export function OfficeRequestWorkspacePage() { const { id } = useParams(); const [data, setData] = useState<any>(null); useDocumentTitle('Request Workspace'); useEffect(() => { api<any>(`/api/office/requests/${id}`).then(setData).catch(() => setData(null)); }, [id]); return <div className="space-y-5"><PageHeader title="Request Workspace" subtitle="Review the request, timeline, requester context, and safe operational actions" /><Surface>{data ? <><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-sm">{data.requestNumber || `#${data.id}`}</p><h2 className="text-xl font-semibold">{data.title}</h2></div><StatusPill tone={statusToneFor(data.status)}>{data.status}</StatusPill></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase text-ink-muted">Requester</dt><dd>{data.student?.name || 'Faculty requester'}</dd></div><div><dt className="text-xs uppercase text-ink-muted">Service</dt><dd>{data.type?.label || data.requestTypeLabel || 'Office service'}</dd></div></dl><div className="mt-6"><h3 className="font-semibold">Timeline</h3><p className="mt-2 text-sm text-ink-muted">{data.timeline?.length || 0} workflow events recorded.</p></div></> : <p className="text-sm text-ink-muted">Loading request workspace…</p>}</Surface></div>; }

export function OfficeDocumentsPage() { const [rows, setRows] = useState<any[]>([]); useDocumentTitle('Issued Documents'); useEffect(() => { api<{items:any[]}>('/api/office/documents').then(d => setRows(d.items)).catch(() => setRows([])); }, []); return <div className="space-y-5"><PageHeader title="Issued Documents" subtitle="Tenant-scoped issued document register" /><Surface className="overflow-x-auto p-0"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-ink-muted"><tr><th className="p-3">Number</th><th className="p-3">Type</th><th className="p-3">Status</th><th className="p-3">Issued</th></tr></thead><tbody>{rows.map(r => <tr className="border-t border-border" key={r.id}><td className="p-3 font-mono">{r.certificate_number}</td><td className="p-3">{r.document_type}</td><td className="p-3"><StatusPill tone={statusToneFor(r.status)}>{r.status}</StatusPill></td><td className="p-3">{String(r.issued_at || '').slice(0, 10)}</td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-sm text-ink-muted">No issued documents.</p>}</Surface></div>; }

export function OfficeRegisterPage({ kind }: { kind: 'inward'|'outward' }) { const [rows,setRows]=useState<any[]>([]); const [form,setForm]=useState({sender:'',recipient:'',subject:'',organization:''}); const path=kind==='inward' ? 'inward':'outward'; useDocumentTitle(kind==='inward'?'Inward Register':'Outward Register'); const load=()=>api<{items:any[]}>(`/api/office/${path}`).then(d=>setRows(d.items)); useEffect(()=>{load()},[]); async function create(){ await api(`/api/office/${path}`,{method:'POST',body:JSON.stringify(kind==='inward'?form:{...form,recipient:form.recipient})}); setForm({sender:'',recipient:'',subject:'',organization:''}); load(); } return <div className="space-y-5"><PageHeader title={kind==='inward'?'Inward Register':'Outward & Dispatch'} subtitle="Tenant-scoped institutional correspondence register" /><Surface><div className="grid gap-2 md:grid-cols-4"><Input placeholder={kind==='inward'?'Sender':'Recipient'} value={kind==='inward'?form.sender:form.recipient} onChange={e=>setForm({...form,[kind==='inward'?'sender':'recipient']:e.target.value})}/><Input placeholder="Organization" value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})}/><Input placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><Button onClick={create}>Register</Button></div></Surface><Surface className="overflow-x-auto p-0"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-ink-muted"><tr><th className="p-3">Number</th><th className="p-3">Party</th><th className="p-3">Subject</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-t border-border" key={r.id}><td className="p-3 font-mono text-xs">{r.inward_number||r.outward_number}</td><td className="p-3">{r.sender||r.recipient}<div className="text-xs text-ink-muted">{r.organization}</div></td><td className="p-3">{r.subject}</td><td className="p-3"><StatusPill tone={statusToneFor(r.status||r.dispatch_state)}>{r.status||r.dispatch_state}</StatusPill></td></tr>)}</tbody></table></Surface></div>; }

export function OfficeFilesPage() { const [rows,setRows]=useState<any[]>([]); useDocumentTitle('Office Files'); useEffect(()=>{api<{items:any[]}>('/api/office/files').then(d=>setRows(d.items))},[]); return <div className="space-y-5"><PageHeader title="Administrative Files" subtitle="See the current custodian and movement state of office files" /><Surface className="overflow-x-auto p-0"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-ink-muted"><tr><th className="p-3">File</th><th className="p-3">Title</th><th className="p-3">Custodian</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-t border-border" key={r.id}><td className="p-3 font-mono">{r.file_number}</td><td className="p-3">{r.title}</td><td className="p-3">{r.current_custodian||'Office'}</td><td className="p-3"><StatusPill tone={statusToneFor(r.status)}>{r.status}</StatusPill></td></tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-sm text-ink-muted">No administrative files registered.</p>}</Surface></div>; }
